2020-01-07 10:36:44,960 ERROR: Exception on /user/fira [GET] [in c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: followers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\routes.py", line 82, in user
    return render_template('user.html',user=user, posts=posts)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\templates\user.html", line 14, in root
    {% elif not current_user.is_following(user) %}
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\templates\base.html", line 54, in root
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\templates\user.html", line 41, in block_content
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\orm\dynamic.py", line 335, in count
    return self._clone(sess).count()
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\orm\query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in scalar
    ret = self.one()
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\orm\query.py", line 3325, in one
    ret = self.one_or_none()
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\orm\query.py", line 3294, in one_or_none
    ret = list(self)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\orm\query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\orm\query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\vuno\srv\learing.python\python\mypy\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: followers
[SQL: SELECT count(*) AS count_1 
FROM (SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user, followers 
WHERE followers.followed_id = ? AND followers.follower_id = user.id) AS anon_1]
[parameters: (3,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-01-08 10:14:29,063 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:48]
2020-01-08 10:15:32,554 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:48]
2020-01-08 10:15:50,216 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:48]
2020-01-08 10:16:19,845 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:48]
2020-01-08 10:17:10,789 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:48]
2020-01-08 11:00:46,046 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 11:02:15,488 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 12:56:32,988 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 13:00:47,154 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 13:01:07,578 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 13:07:05,731 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 13:13:32,323 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 13:14:56,707 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 13:16:57,728 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-08 13:21:41,118 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:50]
2020-01-09 10:19:38,842 INFO: Microblog startup [in C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\__init__.py:55]
